# install with conda env create -f environment.yml
name: 'vanparks_finder'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel=6.29.5
  - altair-all=5.5.0
  - dash=2.18.2
  - dash-bootstrap-components=1.7.1
  - plotly=6.0.0 
  - tabulate=0.9.0
  - pip
  - pip:
      - dash-vega-components==0.11.0
